import "./globals.css";
import { Providers } from "@/components/providers/providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-dark text-light px-4">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
